### ISSUE TITLE
Did you try learning the GeM pooling power?

### ISSUE THREAD

**Issue by andrefaraujo** [lyakaap/Landmark2019-1st-and-3rd-Place-Solution#7]
Hi @lyakaap ,

In your [paper](https://arxiv.org/pdf/1906.04087.pdf), you mention that 

> "p of GeM is set to 3.0 and fixed during the training"

I am wondering if you tried learning the `p` parameter, and if that produced better/worse results, and what this parameter value converged to. 

Thanks!

**Comment by lyakaap** [comment]
@andrefaraujo
I didn't fix the `p` at first, but it made training unstable and its result was as not good as the fixed version (I can't remember regarding the precise `p` value, but it was around 3). So I chose to stick using the fixed version for entire experiments.
It was a bit surprising since many papers say they use learnable `p` AFAIK.
